#!/usr/bin/env python3
"""Summarizes run_suite.sh's raw trial output into a Markdown table.
Only reads files under a results directory, never edits them.

Two raw formats are parsed, both saved by run_suite.sh as
<workload>/trial_N.txt:
  - redis-benchmark -q output, e.g. "SET: 26936.03 requests per second,
    p50=1.687 msec" (its final summary line; earlier progress lines are
    ignored).
  - bench_loadgen's two-line CSV (a header line, then one data line) --
    see loadgen.cpp's print_results_csv().

Usage: summarize.py <results_dir> [--out summary.md]
<results_dir> is the --out directory a run_suite.sh invocation was given
(it contains one subdirectory per --server value, each holding one
subdirectory per workload name).
"""
import argparse
import csv
import io
import re
import statistics
import sys
from pathlib import Path

# label before the colon isn't captured or anchored to line start, since a
# custom rb-custom label can itself contain colons (e.g. "h:__rand_int__")
REDIS_BENCHMARK_LINE = re.compile(r":\s+([\d.]+)\s+requests per second(?:,\s*p50=([\d.]+)\s*msec)?")


def parse_redis_benchmark(text: str):
    """Returns (throughput_rps, p50_us) from the last matching summary line, or None."""
    matches = REDIS_BENCHMARK_LINE.findall(text)
    if not matches:
        return None
    rps, p50_ms = matches[-1]
    p50_us = float(p50_ms) * 1000.0 if p50_ms else None
    return float(rps), p50_us


def parse_loadgen_csv(text: str):
    """Returns (throughput_rps, p50_us) from bench_loadgen's CSV output, or None."""
    lines = [line for line in text.splitlines() if line.strip()]
    if len(lines) < 2 or "throughput_rps" not in lines[0]:
        return None
    reader = csv.DictReader(io.StringIO("\n".join(lines[:2])))
    row = next(reader, None)
    if row is None:
        return None
    return float(row["throughput_rps"]), float(row["p50_us"])


def parse_trial_file(path: Path):
    text = path.read_text(errors="replace")
    result = parse_loadgen_csv(text)
    if result is not None:
        return result
    return parse_redis_benchmark(text)


def fmt(values):
    if not values:
        return "no data"
    if len(values) == 1:
        return f"{values[0]:.1f}"
    return f"{statistics.median(values):.1f} [{min(values):.1f}-{max(values):.1f}]"


def summarize_server(server_dir: Path):
    rows = []
    if not server_dir.is_dir():
        return rows
    for workload_dir in sorted(server_dir.iterdir()):
        if not workload_dir.is_dir():
            continue
        throughputs, p50s = [], []
        for trial_file in sorted(workload_dir.glob("trial_*.txt")):
            parsed = parse_trial_file(trial_file)
            if parsed is None:
                print(f"summarize.py: WARNING: could not parse {trial_file}", file=sys.stderr)
                continue
            rps, p50_us = parsed
            throughputs.append(rps)
            if p50_us is not None:
                p50s.append(p50_us)
        if not throughputs:
            continue
        rows.append((workload_dir.name, throughputs, p50s))
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("results_dir", type=Path)
    parser.add_argument("--out", type=Path, default=None, help="write Markdown here instead of stdout")
    args = parser.parse_args()

    if not args.results_dir.is_dir():
        print(f"summarize.py: {args.results_dir} is not a directory", file=sys.stderr)
        return 1

    servers = [d.name for d in sorted(args.results_dir.iterdir()) if d.is_dir()]
    if not servers:
        print(f"summarize.py: no server subdirectories found under {args.results_dir}", file=sys.stderr)
        return 1

    lines = [f"# Benchmark summary: {args.results_dir.name}", ""]
    lines.append(
        "Generated by bench/scripts/summarize.py from raw trial output under "
        f"`{args.results_dir}`. This table is only as trustworthy as the raw "
        "files it was generated from -- trace any surprising number back to "
        "its `trial_N.txt`."
    )
    lines.append("")

    for server in servers:
        lines.append(f"## {server}")
        lines.append("")
        lines.append("| workload | throughput (req/s), median [min-max] | p50 latency (us), median [min-max] |")
        lines.append("|---|---|---|")
        rows = summarize_server(args.results_dir / server)
        if not rows:
            lines.append("| _(no parseable trials found)_ | | |")
        for name, throughputs, p50s in rows:
            lines.append(f"| {name} | {fmt(throughputs)} | {fmt(p50s)} |")
        lines.append("")

    output = "\n".join(lines) + "\n"
    if args.out:
        args.out.write_text(output)
        print(f"summarize.py: wrote {args.out}")
    else:
        print(output, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
